services:
  app:
    build:
      context: ./lufthansa-url-shortener-backend
    container_name: lufthansa-url-shortener-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./lufthansa-url-shortener-backend:/var/www
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "
      cp .env.example .env &&
      php artisan key:generate &&
      sleep 15 &&
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 &&
      php artisan schedule:work
      "
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=lufthansa_db
      - DB_PORT=3306
      - DB_DATABASE=lufthansa_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
  
  db:
    image: mysql:8
    container_name: lufthansa_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lufthansa_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "0.0.0.0:3308:3306"

  frontend:
    build:
      context: ./lufthansa-url-shortener-front
    container_name: lufthansa-url-shortener-front
    restart: unless-stopped
    volumes:
      - ./lufthansa-url-shortener-front:/app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - app